/**
 * Predefined Scenarios and Station Presets for LORAN LAB
 * 
 * Accurately reflects operational status as of 2026:
 * - US & Canada chains terminated in 2010.
 * - Northwest European chain decommissioned December 31, 2015 (Sylt, Lessay closed; Anthorn retained for timing).
 * - China, Russia (Chayka), and Saudi Arabia operate active modernized eLoran chains.
 * - South Korea is actively upgrading its eLoran infrastructure.
 */

export const PRESET_SCENARIOS = {
  jakarta_baseline: {
    id: 'jakarta_baseline',
    name: 'Jakarta Maritime Testbed (Synthetic / Illustrative)',
    status: 'synthetic',
    description: 'Reference 3-station chain around Jakarta Bay. Ideal for initial TDOA geometry, harbor entrance and approach (HEA) studies, and baseline extension tests.',
    center: [106.816666, -6.200000],
    zoom: 9,
    masters: [
      {
        role: 'master',
        label: 'M1-TanjungPriok',
        lat: -6.100000,
        lng: 106.880000,
        txDbm: 20,
        griMs: 1000,
        offsetSec: 0,
        phaseSec: 0,
        ddsEnabled: true,
        clock: { type: 'gps-disciplined', biasSec: 0, driftPerSec: 0 },
        diffCorrections: { enabled: true, avgMeters: 4.5 },
        asfMeters: 12,
        asfFormula: '15 * sin((lat / 10) * pi)',
      },
    ],
    slaves: [
      {
        role: 'slave',
        label: 'S1-Tangerang',
        lat: -6.180000,
        lng: 106.630000,
        txDbm: 18,
        griMs: 1000,
        offsetSec: 0.011,
        phaseSec: 0,
        ddsEnabled: false,
        clock: { type: 'gps-disciplined', biasSec: 0, driftPerSec: 0 },
        diffCorrections: { enabled: false, avgMeters: 0 },
        asfMeters: 8,
      },
      {
        role: 'slave',
        label: 'S2-Bekasi',
        lat: -6.240000,
        lng: 106.990000,
        txDbm: 18,
        griMs: 1000,
        offsetSec: 0.025,
        phaseSec: 0,
        ddsEnabled: false,
        clock: { type: 'gps-disciplined', biasSec: 0, driftPerSec: 0 },
        diffCorrections: { enabled: false, avgMeters: 0 },
        asfMeters: 10,
      },
    ],
    receivers: [
      {
        role: 'receiver',
        label: 'R1-Vessel',
        lat: -6.150000,
        lng: 106.820000,
        fuseMode: 'fusion',
      },
    ],
  },

  north_sea_historical: {
    id: 'north_sea_historical',
    name: 'North Sea Chain (Historical - Decommissioned Dec 2015)',
    status: 'historical',
    description: 'Historical Northwest European Loran-C/eLoran chain (GRI 6731). Decommissioned on December 31, 2015. Sylt (Germany) and Lessay (France) were permanently shut down. Anthorn (UK) transmitter was retained solely for timing broadcast (UTC transfer). Demonstrates that a single transmitter provides time synchronization but cannot solve for a 2D position fix.',
    center: [3.5, 53.5],
    zoom: 5.5,
    masters: [
      {
        role: 'master',
        label: 'Sylt-Master (Decomm 2015)',
        lat: 54.960278,
        lng: 8.293611,
        txDbm: 24,
        griMs: 6731,
        offsetSec: 0,
        phaseSec: 0,
        ddsEnabled: true,
        clock: { type: 'cesium', biasSec: 0, driftPerSec: 1e-13 },
        diffCorrections: { enabled: true, avgMeters: 2.1 },
        asfMeters: 5,
        asfFormula: '20 * cos((lng / 5) * pi)',
      },
    ],
    slaves: [
      {
        role: 'slave',
        label: 'Lessay-Slave (Decomm 2015)',
        lat: 49.150000,
        lng: -1.503333,
        txDbm: 24,
        griMs: 6731,
        offsetSec: 0.013,
        phaseSec: 0,
        ddsEnabled: true,
        clock: { type: 'cesium', biasSec: 0, driftPerSec: 1e-13 },
        diffCorrections: { enabled: false, avgMeters: 0 },
        asfMeters: 18,
      },
      {
        role: 'slave',
        label: 'Anthorn-Slave (UK Timing Only)',
        lat: 54.911389,
        lng: -3.278333,
        txDbm: 22,
        griMs: 6731,
        offsetSec: 0.027,
        phaseSec: 0,
        ddsEnabled: true,
        clock: { type: 'cesium', biasSec: 0, driftPerSec: 1e-13 },
        diffCorrections: { enabled: false, avgMeters: 0 },
        asfMeters: 12,
      },
    ],
    receivers: [
      {
        role: 'receiver',
        label: 'NorthSea-Vessel',
        lat: 53.800000,
        lng: 3.200000,
        fuseMode: 'fusion',
      },
    ],
  },

  bohai_yellow_sea_active: {
    id: 'bohai_yellow_sea_active',
    name: 'Bohai & Yellow Sea Chain — GRI 7430 (Active)',
    status: 'active',
    description: 'Active Chinese eLoran North Chain (GRI 7430). Master: Rongcheng (37°04\'N 122°19\'E). Secondaries: Xuancheng (31°04\'N 118°53\'E) and Helong (42°43\'N 128°55\'E). Coordinates from NGA Pub 117 (Radio Aids to Navigation, Chapter 6, 2023 ed.) and Zhang et al. (2024) ILA-42 paper. Transmits navigation pulses plus 9th-pulse LDC differential corrections. GRI = 7430 (74.3 ms group interval). Note: GRI 6780 is the separate South China Sea chain (Hexian master).',
    center: [121.5, 36.5],
    zoom: 6,
    masters: [
      {
        role: 'master',
        // Source: NGA Pub 117 (2023), Chapter 6 — Chinese Loran-C/eLoran stations
        // Rongcheng (荣成) 37°04'N 122°19'E → 37.0667°N, 122.3167°E
        label: 'Rongcheng-M (Active)',
        lat: 37.066667,
        lng: 122.316667,
        txDbm: 26,
        griMs: 7430,
        offsetSec: 0,
        phaseSec: 0,
        ddsEnabled: true,
        clock: { type: 'cesium', biasSec: 0, driftPerSec: 1e-14 },
        diffCorrections: { enabled: true, avgMeters: 1.8 },
        asfMeters: 8,
      },
    ],
    slaves: [
      {
        role: 'slave',
        // Source: NGA Pub 117 (2023) — Xuancheng (宣城) 31°04'N 118°53'E → 31.0667°N, 118.8833°E
        label: 'Xuancheng-S1 (Active)',
        lat: 31.066667,
        lng: 118.883333,
        txDbm: 26,
        griMs: 7430,
        offsetSec: 0.012,
        phaseSec: 0,
        ddsEnabled: true,
        clock: { type: 'cesium', biasSec: 0, driftPerSec: 1e-14 },
        diffCorrections: { enabled: false, avgMeters: 0 },
        asfMeters: 15,
      },
      {
        role: 'slave',
        // Source: NGA Pub 117 (2023) — Helong (和龙) 42°43'N 128°55'E → 42.7167°N, 128.9167°E
        label: 'Helong-S2 (Active)',
        lat: 42.716667,
        lng: 128.916667,
        txDbm: 26,
        griMs: 7430,
        offsetSec: 0.028,
        phaseSec: 0,
        ddsEnabled: true,
        clock: { type: 'cesium', biasSec: 0, driftPerSec: 1e-14 },
        diffCorrections: { enabled: false, avgMeters: 0 },
        asfMeters: 22,
      },
    ],
    receivers: [
      {
        role: 'receiver',
        label: 'Cargo-Vessel-Bohai',
        lat: 38.200000,
        lng: 121.000000,
        fuseMode: 'fusion',
      },
    ],
  },

  high_gdop: {
    id: 'high_gdop',
    name: 'Poor Geometry (High GDOP Collinear Scenario)',
    status: 'synthetic',
    description: 'Collinear transmitter layout causing high Geometric Dilution of Precision (GDOP) and severely elongated error ellipses along the baseline axis.',
    center: [107.0, -6.2],
    zoom: 8,
    masters: [
      {
        role: 'master',
        label: 'M-Collinear',
        lat: -6.200000,
        lng: 106.500000,
        txDbm: 20,
        griMs: 1000,
        offsetSec: 0,
        ddsEnabled: true,
        clock: { type: 'gps-disciplined', biasSec: 0, driftPerSec: 0 },
      },
    ],
    slaves: [
      {
        role: 'slave',
        label: 'S1-Linear',
        lat: -6.205000,
        lng: 106.800000,
        txDbm: 18,
        offsetSec: 0.01,
        ddsEnabled: false,
        clock: { type: 'gps-disciplined', biasSec: 0, driftPerSec: 0 },
      },
      {
        role: 'slave',
        label: 'S2-Linear',
        lat: -6.210000,
        lng: 107.100000,
        txDbm: 18,
        offsetSec: 0.02,
        ddsEnabled: false,
        clock: { type: 'gps-disciplined', biasSec: 0, driftPerSec: 0 },
      },
    ],
    receivers: [
      {
        role: 'receiver',
        label: 'R-Divergent',
        lat: -6.600000,
        lng: 106.800000,
        fuseMode: 'eLoran',
      },
    ],
  },

  gnss_denied: {
    id: 'gnss_denied',
    name: 'GNSS-Denied Maritime Resilience (Synthetic Testbed)',
    status: 'synthetic',
    description: 'Demonstrates eLoran autonomous resilient PNT when satellite GNSS signals are degraded, jammed, or spoofed.',
    center: [106.8, -6.15],
    zoom: 9,
    masters: [
      {
        role: 'master',
        label: 'M-Secure',
        lat: -6.080000,
        lng: 106.750000,
        txDbm: 22,
        griMs: 1000,
        offsetSec: 0,
        ddsEnabled: true,
        clock: { type: 'cesium', biasSec: 0, driftPerSec: 0 },
        diffCorrections: { enabled: true, avgMeters: 6.2 },
        asfMeters: 25,
      },
    ],
    slaves: [
      {
        role: 'slave',
        label: 'S1-Coast',
        lat: -6.150000,
        lng: 106.550000,
        txDbm: 20,
        offsetSec: 0.015,
        ddsEnabled: true,
        clock: { type: 'cesium', biasSec: 0, driftPerSec: 0 },
      },
      {
        role: 'slave',
        label: 'S2-Island',
        lat: -5.950000,
        lng: 106.850000,
        txDbm: 20,
        offsetSec: 0.028,
        ddsEnabled: true,
        clock: { type: 'cesium', biasSec: 0, driftPerSec: 0 },
      },
    ],
    receivers: [
      {
        role: 'receiver',
        label: 'Autonomous-Vessel',
        lat: -6.120000,
        lng: 106.700000,
        fuseMode: 'eLoran',
      },
    ],
  },
};
