/**
 * Predefined Scenarios and Station Presets for LORAN LAB
 */

export const PRESET_SCENARIOS = {
  jakarta_baseline: {
    id: 'jakarta_baseline',
    name: 'Jakarta Baseline Chain',
    description: 'Reference 3-station chain around Jakarta Bay. Ideal for initial TDOA geometry and baseline extension tests.',
    center: [106.816666, -6.200000],
    zoom: 9,
    masters: [
      {
        role: 'master',
        label: 'M1-TanjungPriok',
        lat: -6.100000,
        lng: 106.880000,
        txDbm: 20,
        griMs: 1000,
        offsetSec: 0,
        phaseSec: 0,
        ddsEnabled: true,
        clock: { type: 'gps-disciplined', biasSec: 0, driftPerSec: 0 },
        diffCorrections: { enabled: true, avgMeters: 4.5 },
        asfMeters: 12,
        asfFormula: '15 * sin((lat / 10) * pi)',
      },
    ],
    slaves: [
      {
        role: 'slave',
        label: 'S1-Tangerang',
        lat: -6.180000,
        lng: 106.630000,
        txDbm: 18,
        griMs: 1000,
        offsetSec: 0.011,
        phaseSec: 0,
        ddsEnabled: false,
        clock: { type: 'gps-disciplined', biasSec: 0, driftPerSec: 0 },
        diffCorrections: { enabled: false, avgMeters: 0 },
        asfMeters: 8,
      },
      {
        role: 'slave',
        label: 'S2-Bekasi',
        lat: -6.240000,
        lng: 106.990000,
        txDbm: 18,
        griMs: 1000,
        offsetSec: 0.025,
        phaseSec: 0,
        ddsEnabled: false,
        clock: { type: 'gps-disciplined', biasSec: 0, driftPerSec: 0 },
        diffCorrections: { enabled: false, avgMeters: 0 },
        asfMeters: 10,
      },
    ],
    receivers: [
      {
        role: 'receiver',
        label: 'R1-Vessel',
        lat: -6.150000,
        lng: 106.820000,
        fuseMode: 'fusion',
      },
    ],
  },

  north_sea: {
    id: 'north_sea',
    name: 'North Sea European eLoran Chain',
    description: 'Realistic multi-nation European eLoran network (Anthorn UK, Sylt Germany, Lessay France). High maritime coverage.',
    center: [3.5, 53.5],
    zoom: 5.5,
    masters: [
      {
        role: 'master',
        label: 'Anthorn-M',
        lat: 54.911389,
        lng: -3.278333,
        txDbm: 24,
        griMs: 6731,
        offsetSec: 0,
        phaseSec: 0,
        ddsEnabled: true,
        clock: { type: 'cesium', biasSec: 0, driftPerSec: 1e-13 },
        diffCorrections: { enabled: true, avgMeters: 2.1 },
        asfMeters: 5,
        asfFormula: '20 * cos((lng / 5) * pi)',
      },
    ],
    slaves: [
      {
        role: 'slave',
        label: 'Sylt-W',
        lat: 54.960278,
        lng: 8.293611,
        txDbm: 22,
        griMs: 6731,
        offsetSec: 0.012,
        phaseSec: 0,
        ddsEnabled: true,
        clock: { type: 'cesium', biasSec: 0, driftPerSec: 1e-13 },
        diffCorrections: { enabled: false, avgMeters: 0 },
        asfMeters: 15,
      },
      {
        role: 'slave',
        label: 'Lessay-X',
        lat: 49.150000,
        lng: -1.503333,
        txDbm: 22,
        griMs: 6731,
        offsetSec: 0.027,
        phaseSec: 0,
        ddsEnabled: true,
        clock: { type: 'cesium', biasSec: 0, driftPerSec: 1e-13 },
        diffCorrections: { enabled: false, avgMeters: 0 },
        asfMeters: 18,
      },
    ],
    receivers: [
      {
        role: 'receiver',
        label: 'Tanker-Alpha',
        lat: 53.800000,
        lng: 3.200000,
        fuseMode: 'fusion',
      },
    ],
  },

  high_gdop: {
    id: 'high_gdop',
    name: 'Poor Geometry (High GDOP Scenario)',
    description: 'Almost collinear stations causing extreme geometric dilution of precision and elongated error ellipses.',
    center: [107.0, -6.2],
    zoom: 8,
    masters: [
      {
        role: 'master',
        label: 'M-Collinear',
        lat: -6.200000,
        lng: 106.500000,
        txDbm: 20,
        griMs: 1000,
        offsetSec: 0,
        ddsEnabled: true,
        clock: { type: 'gps-disciplined', biasSec: 0, driftPerSec: 0 },
      },
    ],
    slaves: [
      {
        role: 'slave',
        label: 'S1-Linear',
        lat: -6.205000,
        lng: 106.800000,
        txDbm: 18,
        offsetSec: 0.01,
        ddsEnabled: false,
        clock: { type: 'gps-disciplined', biasSec: 0, driftPerSec: 0 },
      },
      {
        role: 'slave',
        label: 'S2-Linear',
        lat: -6.210000,
        lng: 107.100000,
        txDbm: 18,
        offsetSec: 0.02,
        ddsEnabled: false,
        clock: { type: 'gps-disciplined', biasSec: 0, driftPerSec: 0 },
      },
    ],
    receivers: [
      {
        role: 'receiver',
        label: 'R-Divergent',
        lat: -6.600000,
        lng: 106.800000,
        fuseMode: 'eLoran',
      },
    ],
  },

  gnss_denied: {
    id: 'gnss_denied',
    name: 'GNSS-Denied Maritime Resilience',
    description: 'Demonstrates eLoran autonomous backup when GPS is spoofed or jammed. Compares eLoran vs GNSS error.',
    center: [106.8, -6.15],
    zoom: 9,
    masters: [
      {
        role: 'master',
        label: 'M-Secure',
        lat: -6.080000,
        lng: 106.750000,
        txDbm: 22,
        griMs: 1000,
        offsetSec: 0,
        ddsEnabled: true,
        clock: { type: 'cesium', biasSec: 0, driftPerSec: 0 },
        diffCorrections: { enabled: true, avgMeters: 6.2 },
        asfMeters: 25,
      },
    ],
    slaves: [
      {
        role: 'slave',
        label: 'S1-Coast',
        lat: -6.150000,
        lng: 106.550000,
        txDbm: 20,
        offsetSec: 0.015,
        ddsEnabled: true,
        clock: { type: 'cesium', biasSec: 0, driftPerSec: 0 },
      },
      {
        role: 'slave',
        label: 'S2-Island',
        lat: -5.950000,
        lng: 106.850000,
        txDbm: 20,
        offsetSec: 0.028,
        ddsEnabled: true,
        clock: { type: 'cesium', biasSec: 0, driftPerSec: 0 },
      },
    ],
    receivers: [
      {
        role: 'receiver',
        label: 'Autonomous-Vessel',
        lat: -6.120000,
        lng: 106.700000,
        fuseMode: 'eLoran',
      },
    ],
  },
};
