import { describe, it, expect } from 'vitest';
import { exportScenarioGeoJson, importScenarioGeoJson } from '../stations.js';

describe('Scenario GeoJSON Exporter and Importer Backward Compatibility', () => {
  const sampleMasters = [
    { role: 'master', label: 'M1', lat: -6.1754, lng: 106.8272, txDbm: 20, griMs: 1000 },
  ];
  const sampleSlaves = [
    { role: 'slave', label: 'S1', lat: -5.9, lng: 106.5, txDbm: 18, griMs: 1000 },
    { role: 'slave', label: 'S2', lat: -6.4, lng: 107.1, txDbm: 18, griMs: 1000 },
  ];
  const sampleReceivers = [
    { role: 'receiver', label: 'R1', lat: -6.2, lng: 106.8 },
  ];

  it('exports GeoJSON with metadata generator SIMULORAN', () => {
    const geojson = exportScenarioGeoJson(sampleMasters, sampleSlaves, sampleReceivers);
    expect(geojson.type).toBe('FeatureCollection');
    expect(geojson.metadata.generator).toBe('SIMULORAN');
    expect(geojson.metadata.stationCount).toBe(4);
    expect(geojson.features.length).toBe(4);
  });

  it('imports scenario generated by SIMULORAN', () => {
    const exported = exportScenarioGeoJson(sampleMasters, sampleSlaves, sampleReceivers);
    const imported = importScenarioGeoJson(exported);

    expect(imported.errors).toEqual([]);
    expect(imported.masters.length).toBe(1);
    expect(imported.slaves.length).toBe(2);
    expect(imported.receivers.length).toBe(1);
    expect(imported.masters[0].label).toBe('M1');
  });

  it('accepts legacy files generated by LORAN LAB fixture with zero errors', () => {
    const legacyFixture = {
      type: 'FeatureCollection',
      metadata: {
        generator: 'LORAN LAB',
        timestamp: '2026-09-20T10:00:00.000Z',
        stationCount: 3,
      },
      features: [
        {
          type: 'Feature',
          geometry: { type: 'Point', coordinates: [106.8272, -6.1754] },
          properties: { role: 'master', label: 'Legacy-Master', txDbm: 20, griMs: 1000 },
        },
        {
          type: 'Feature',
          geometry: { type: 'Point', coordinates: [106.5, -5.9] },
          properties: { role: 'slave', label: 'Legacy-Slave', txDbm: 18, griMs: 1000 },
        },
        {
          type: 'Feature',
          geometry: { type: 'Point', coordinates: [106.8, -6.2] },
          properties: { role: 'receiver', label: 'Legacy-Rx' },
        },
      ],
    };

    const imported = importScenarioGeoJson(legacyFixture);
    expect(imported.errors).toEqual([]);
    expect(imported.masters.length).toBe(1);
    expect(imported.masters[0].label).toBe('Legacy-Master');
    expect(imported.slaves.length).toBe(1);
    expect(imported.slaves[0].label).toBe('Legacy-Slave');
    expect(imported.receivers.length).toBe(1);
    expect(imported.receivers[0].label).toBe('Legacy-Rx');
  });
});
